USE project_ensf_607_608;

-- DROP TABLE CUSTOMER;
-- DROP TABLE SUPPLIER;
-- DROP TABLE INTERNATIONAL;
-- DROP TABLE TOOL;
-- DROP TABLE ELECTRICAL;
-- DROP TABLE TOOLSORDER;
-- DROP TABLE ORDERLINE;
-- DROP TABLE PURCHASES;

CREATE TABLE CUSTOMER (
	CustomerId INT AUTO_INCREMENT,
    LName VARCHAR(20) NOT NULL,
    FName VARCHAR(20) NOT NULL,
    Type CHAR NOT NULL,
    PhoneNum VARCHAR(12) NOT NULL,
    Address VARCHAR(50) NOT NULL,
    PostalCode VARCHAR(7),
    PRIMARY KEY(CustomerId),
    CHECK(CustomerId > 0)
);

CREATE TABLE SUPPLIER (
	SupplierId INT AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Type VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    CName VARCHAR(255) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    PRIMARY KEY(SupplierId),
	CHECK(SupplierId > 0)
);

CREATE TABLE INTERNATIONAL (
	SupplierId INT NOT NULL,
    ImportTax DECIMAL(3, 2) NOT NULL,
    FOREIGN KEY(SupplierId) REFERENCES SUPPLIER(SupplierId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(SupplierId)
);

CREATE TABLE TOOL (
	ToolId INT AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Type VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(5, 2) NOT NULL,
    SupplierId INT,
    FOREIGN KEY(SupplierId) REFERENCES SUPPLIER(SupplierId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ToolId),
	CHECK(ToolId > 0)
);

CREATE TABLE ELECTRICAL (
	ToolId INT NOT NULL,
    PowerType VARCHAR(255) NOT NULL,
    FOREIGN KEY(ToolId) REFERENCES TOOL(ToolId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(ToolId)
);

CREATE TABLE TOOLSORDER (
	OrderId INT NOT NULL,
    Date DATE NOT NULL,
    PRIMARY KEY(OrderId),
    CHECK(OrderId>=10000),
    CHECK(OrderId<99999)
);

CREATE TABLE ORDERLINE (
	OrderId INT NOT NULL,
    ToolId INT NOT NULL,
    SupplierId INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY(OrderId) REFERENCES TOOLSORDER(OrderId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ToolId) REFERENCES TOOL(ToolId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(SupplierId) REFERENCES SUPPLIER(SupplierId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(OrderId, ToolId)
);

CREATE TABLE PURCHASES (
	CustomerId INT NOT NULL,
    ToolId INT NOT NULL,
    Date DATE NOT NULL,
    FOREIGN KEY(CustomerId) REFERENCES CUSTOMER(CustomerId) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ToolId) REFERENCES TOOL(ToolId) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY(CustomerId, ToolId, Date)
);