USE project_ensf_607_608;

-- DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER (
	CustomerId INT AUTO_INCREMENT,
    LName VARCHAR(20) NOT NULL,
    FName VARCHAR(20) NOT NULL,
    Type CHAR NOT NULL,
    PhoneNum VARCHAR(12) NOT NULL,
    Address VARCHAR(50) NOT NULL,
    PostalCode VARCHAR(7),
    PRIMARY KEY(CustomerId)
);